/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContestRouteImport } from './routes/contest'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ContestIndexRouteImport } from './routes/contest.index'
import { Route as ContestQidRouteImport } from './routes/contest.$qid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestRoute = ContestRouteImport.update({
  id: '/contest',
  path: '/contest',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestIndexRoute = ContestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContestRoute,
} as any)
const ContestQidRoute = ContestQidRouteImport.update({
  id: '/$qid',
  path: '/$qid',
  getParentRoute: () => ContestRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contest': typeof ContestRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/recovery': typeof RecoveryRoute
  '/register': typeof RegisterRoute
  '/contest/$qid': typeof ContestQidRoute
  '/contest/': typeof ContestIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/leaderboard': typeof LeaderboardRoute
  '/recovery': typeof RecoveryRoute
  '/register': typeof RegisterRoute
  '/contest/$qid': typeof ContestQidRoute
  '/contest': typeof ContestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contest': typeof ContestRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/recovery': typeof RecoveryRoute
  '/register': typeof RegisterRoute
  '/contest/$qid': typeof ContestQidRoute
  '/contest/': typeof ContestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contest'
    | '/leaderboard'
    | '/recovery'
    | '/register'
    | '/contest/$qid'
    | '/contest/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/leaderboard'
    | '/recovery'
    | '/register'
    | '/contest/$qid'
    | '/contest'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contest'
    | '/leaderboard'
    | '/recovery'
    | '/register'
    | '/contest/$qid'
    | '/contest/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContestRoute: typeof ContestRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  RecoveryRoute: typeof RecoveryRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contest': {
      id: '/contest'
      path: '/contest'
      fullPath: '/contest'
      preLoaderRoute: typeof ContestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contest/': {
      id: '/contest/'
      path: '/'
      fullPath: '/contest/'
      preLoaderRoute: typeof ContestIndexRouteImport
      parentRoute: typeof ContestRoute
    }
    '/contest/$qid': {
      id: '/contest/$qid'
      path: '/$qid'
      fullPath: '/contest/$qid'
      preLoaderRoute: typeof ContestQidRouteImport
      parentRoute: typeof ContestRoute
    }
  }
}

interface ContestRouteChildren {
  ContestQidRoute: typeof ContestQidRoute
  ContestIndexRoute: typeof ContestIndexRoute
}

const ContestRouteChildren: ContestRouteChildren = {
  ContestQidRoute: ContestQidRoute,
  ContestIndexRoute: ContestIndexRoute,
}

const ContestRouteWithChildren =
  ContestRoute._addFileChildren(ContestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContestRoute: ContestRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  RecoveryRoute: RecoveryRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
